routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Intervention\Image\Facades\Image;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth'])->group(function () {
    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_view');

        Route::get('/edit/{id}', [UserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_edit');

        Route::get('/create', [UserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::post('/', [UserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_store');

        Route::delete('/{user}', [UserController::class, 'destroy'])
            ->name('delete')
            ->middleware(['permission:user_delete', 'check.user']);

        Route::put('/{id}', [UserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('users/{id}', [UserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_show');
    });

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [RoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_view');

        Route::get('/edit/{id}', [RoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_edit');

        Route::get('/create', [RoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [RoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_store');

        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:role_delete');

        Route::put('/{id}', [RoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('users/{id}', [RoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_show');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_view');

        Route::get('/create', [ProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/edit/{id}', [ProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_edit');

        Route::put('/{id}', [ProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::post('/', [ProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_store');

        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:product_delete');

        Route::get('/{id}', [ProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_show');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_view');

        Route::get('/create', [CategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::post('/', [CategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_store');

        Route::get('/list', [CategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_view');

        Route::get('/edit/{id}', [CategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_edit');

        Route::put('/{category}', [CategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::delete('/{category}', [CategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');
    });
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table = 'roles';

    protected $fillable = [
        'name',
        'display_name'
    ];

    protected $hidden = [
        'created_at',
        'updated_at'
    ];

    public function permissions()
    {
        return $this->belongsToMany(
            Permisson::class,
            'role_permission',
            'role_id',
            'permission_id'
        );
    }

    public function user()
    {
        return $this->belongsToMany(
            User::class,
            'role_user',
            'role_id',
            'user_id'
        );
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function attachPermission($permissionId)
    {
        return $this->permissions()->attach($permissionId);
    }

    public function syncPermission($permissionId)
    {
        return $this->permissions()->sync($permissionId);
    }

    public function syncUser($user_id)
    {
        return $this->user()->sync($user_id);
    }

    public function detachPermission()
    {
        return $this->permissions()->detach();
    }

    public function detachUser()
    {
        return $this->user()->detach();
    }

    public function getIdPermission($id)
    {
        return $this->permissions()->where('role_id', $id)->pluck('permission_id');
    }

    public function scopeWithoutSuperAdmin($query)
    {
        return $query->where('name', '!=', 'super_admin');
    }
}

app/Http/Controllers/Api/RoleController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Role\RoleRequest;
use App\Http\Resources\RoleCollection;
use App\Http\Resources\RoleResource;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class RoleController extends Controller
{
    protected $role;

    /**
     * @param $role
     */
    public function __construct(Role $role)
    {
        $this->role = $role;
    }

    public function index()
    {
        $roles = $this->role->paginate(5);

        $rolesCollection = new RoleCollection($roles);

        return $this->successResponse($rolesCollection, 'Danh sách sản phẩm!');
    }

    public function store(RoleRequest $request)
    {
        $createRole = $request->all();
        $role = $this->role->create($createRole);
        $RoleResource = new RoleResource($role);
        return $this->successResponse($RoleResource, 'Thêm thành công!');
    }

    public function show($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\RoleRequest;
use App\Services\PermissionService;
use App\Services\RoleService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class RoleController extends Controller
{
    protected RoleService $roleService;

    protected PermissionService $permissionService;

    public function __construct(RoleService $roleService, PermissionService $permissionService)
    {
        $this->roleService = $roleService;

        $this->permissionService = $permissionService;

        View::share('permissions', $this->permissionService->getAll());

        View::share('permissionGroup', $this->permissionService->getWithGroup());
    }

    public function index(Request $request)
    {
        $roles = $this->roleService->getAllRole($request);

        return view('admin.roles.index', compact('roles'));
    }

    public function create()
    {
        return view('admin.roles.create');
    }

    public function store(RoleRequest $request)
    {
        $this->roleService->create($request);

        return redirect()->route('roles.index');
    }

    public function show($id)
    {
        $role = $this->roleService->getRoleId($id);

        return view('admin.roles.show', compact('role'));
    }

    public function edit($id)
    {

        $role = $this->roleService->getRoleId($id);

        $permissionIds = $this->roleService->getPermissionIdRole($id);

        return view('admin.roles.edit', compact('role', 'permissionIds'));
    }

    public function update(RoleRequest $request, $id)
    {
        $this->roleService->update($request, $id);

        return redirect()->route('roles.index');
    }

    public function destroy($id)
    {
        $this->roleService->delete($id);

        return redirect()->route('roles.index');
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Create Role</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Role</li>
                </ol>

                <div class="container">
                    <div class="row justify-content-center">
                        <form action="{{ route('roles.store') }}" method="POST">
                            @csrf

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Name</label>
                                    <input name="name" type="text" class="form-control" placeholder="Name...">
                                    @error('name')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Display_Name</label>
                                    <input name="display_name" type="text" class="form-control"
                                           placeholder="Display Name...">
                                    @error('display_name')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <input class="form-check-input select-all-permission" type="checkbox">
                                <label class="form-label">Permission</label>
                                <div class="row">
                                    <div class="form-check-inline">
                                        @foreach($permissionGroup as $group => $permission)
                                            <div class="col-md-3">
                                                <input class="form-check-input select-item" type="checkbox">
                                                <label class="form-label"><b>{{ $group }}</b></label>
                                                @foreach($permission as $permissionItem)
                                                    <div class="card-text">
                                                        <div class="form-check">
                                                            <input class="form-check-input" type="checkbox"
                                                                   name="display_name_permission[]"
                                                                   value="{{ $permissionItem->id }}">
                                                            <label class="form-check-label" for="flexCheckDefault">
                                                                {{ $permissionItem->display_name }}
                                                            </label>
                                                        </div>
                                                    </div>
                                                @endforeach
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-success">Submit</button>


                        </form>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Update Role</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Role</li>
                </ol>

                <div class="container">
                    <div class="row justify-content-center">
                        <form action="{{route('roles.update',$role->id)}}" method="POST" class="container"  id="form-{{$role->id}}">
                            @method('PUT')
                            @csrf
                            <div class="mb-3">
                                <label class="form-label">Name</label>
                                <input type="text" class="form-control" name="name" value="{{$role->name}}">
                                @error('name')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Display_Name</label>
                                <input type="text" class="form-control" name="display_name"
                                       value="{{$role->display_name}}">
                                @error('display_name')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <input class="form-check-input select-all-permission" type="checkbox">
                                <label class="form-label">Permission</label>
                                <div class="row">
                                    <div class="form-check-inline">
                                        @foreach($permissionGroup as $group => $permission)
                                            <div class="col-md-3">
                                                <input class="form-check-input select-item" type="checkbox"
                                                       id="select-group-permission">
                                                <label class="form-label"><b>{{ $group }}</b></label>
                                                @foreach($permission as $permissionItem)
                                                    <div class="card-text">
                                                        <div class="form-check">
                                                            <input
                                                                {{ $permissionIds->contains($permissionItem->id) ? 'checked' : '' }} class="form-check-input"
                                                                type="checkbox"
                                                                name="display_name_permission[]"
                                                                value="{{ $permissionItem->id }}">
                                                            <label class="form-check-label" for="flexCheckDefault">
                                                                {{ $permissionItem->display_name }}
                                                            </label>
                                                        </div>
                                                    </div>
                                                @endforeach
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </form>
                        <button class="btn btn-success" type="submit" onclick="updateRole({{$role->id}})"
                                style="height: 50px;width: 200px">Update Role</button>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script>
        function updateRole(id) {
            Swal.fire({
                title: 'Do you want to save the changes?',
                showDenyButton: true,
                showCancelButton: true,
                confirmButtonText: 'Save',
                denyButtonText: `Don't save`,
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    event.preventDefault();
                    document.getElementById('form-' + id).submit();
                    Swal.fire('Saved!', '', 'success')
                } else if (result.isDenied) {
                    event.preventDefault();
                    window.history.back();
                    Swal.fire('Changes are not saved', '', 'info')
                }
            })
        }
    </script>
@endpush

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Role Management</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">All Roles</li>
                </ol>
                <div class="container-fluid px-4">
                    @hasPermission('role_create')
                    <a href="{{ route('roles.create') }}" class="btn btn-success">Create New Role</a>
                    @endhasPermission
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <form method="GET" class="m-md-3 d-flex">
                                <input type="search" name="name" value="{{ request('name') }}" class="form-control"
                                       placeholder="search ...">
                                <button type="submit" class="btn btn-primary">
                                    search
                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Permission</th>
                                <th scope="col">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($roles as $role)
                                <tr>
                                    <th scope="row">{{$role->id}}</th>
                                    <td>{{$role->display_name}}</td>
                                    <td>
                                        @foreach($role->permissions as $key=>$permission)
                                            <span style="font-size: 14px" class="text-black">{{ $permission->display_name }}
                                                {{ $key + 1 == $role->permissions->count() ? '.' : ',' }}
                                                {{--                                                {{ $role->permissions->count() }}--}}
                                            </span>
                                        @endforeach
                                    </td>

                                    <td>
                                        @hasPermission('role_show')
                                        <a href="{{route('roles.show',$role->id)}}" class="btn btn-primary"><i
                                                class="far fa-eye"></i></a>
                                        @endhasPermission
                                        @hasPermission('role_edit')
                                        <a href="{{route('roles.edit',$role->id)}}" class="btn btn-success"><i
                                                class="far fa-edit"></i></a>
                                        @endhasPermission
                                        @hasPermission('role_delete')
                                        <button type="submit" class="btn btn-danger btn-delete"
                                                onclick="deleteRole({{$role->id}})"><i
                                                class="fas fa-trash-alt"></i></button>
                                        @endhasPermission
                                        <form action=" {{ route('roles.delete', $role->id) }}" id="form-{{$role->id}}"
                                              method="POST">
                                            @method('DELETE')
                                            @csrf
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                    <p class="font-weight-bold" style="text-align: center"> -- NOT FOUND DATA -- </p>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="container-fluid">
                            {{$roles->links()}}
                        </div>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script>
        function deleteRole(id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    event.preventDefault();
                    document.getElementById('form-' + id).submit();
                    Swal.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/admin/roles/show.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Show Role</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Role</li>
                </ol>

                <div class="container-fluid px4">
                    <div class="row justify-content-center">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Display Name</th>
                                <th scope="col">Permission</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">{{$role->id}}</th>
                                <td>{{$role->name}}</td>
                                <td>{{$role->display_name}}</td>
                                <td>
                                    @foreach($role->permissions as $permission)
                                        <span style="font-size: 12px"
                                              class="badge badge-info">{{ $permission->display_name }}</span>
                                    @endforeach
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection