routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Intervention\Image\Facades\Image;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth'])->group(function () {
    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_view');

        Route::get('/edit/{id}', [UserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_edit');

        Route::get('/create', [UserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::post('/', [UserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_store');

        Route::delete('/{user}', [UserController::class, 'destroy'])
            ->name('delete')
            ->middleware(['permission:user_delete', 'check.user']);

        Route::put('/{id}', [UserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('users/{id}', [UserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_show');
    });

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [RoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_view');

        Route::get('/edit/{id}', [RoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_edit');

        Route::get('/create', [RoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [RoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_store');

        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:role_delete');

        Route::put('/{id}', [RoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('users/{id}', [RoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_show');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_view');

        Route::get('/create', [ProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/edit/{id}', [ProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_edit');

        Route::put('/{id}', [ProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::post('/', [ProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_store');

        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:product_delete');

        Route::get('/{id}', [ProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_show');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_view');

        Route::get('/create', [CategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::post('/', [CategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_store');

        Route::get('/list', [CategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_view');

        Route::get('/edit/{id}', [CategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_edit');

        Route::put('/{category}', [CategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::delete('/{category}', [CategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');
    });
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
@include('admin.layouts.head')

<body class="sb-nav-fixed">
@include('admin.layouts.nav')

<div id="layoutSidenav">
    @include('admin.layouts.sitenav')

    @yield('content')

</div>

@include('admin.layouts.js')
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>
@stack('scripts')
</body>
</html>

resources/views/admin/layouts/head.blade.php
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Admin - @yield('title')</title>

    <!-- Scripts -->
    {{--    <script src="{{ asset('js/app.js') }}" ></script>--}}

    <link href="{{ asset('css/styles.css') }}" rel="stylesheet"/>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.7/dist/sweetalert2.all.min.js"></script>
    <link rel="icon" href="https://www.icon-icon.com/wp-content/uploads/2018/01/1200px-logo_nike.svg_.png" />

</head>

resources/views/admin/layouts/js.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{{ asset('js/scripts.js') }}"></script>
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>--}}
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="{{ asset('js/datatables-simple-demo.js') }}"></script>
<script>

    document.getElementsByClassName('select-all-permission').onclick = function () {
        var checkboxes = document.getElementsByName('display_name_permission[]');
        for (var checkbox of checkboxes) {
            checkbox.checked = this.checked;
        }
    }

    $(".select-all-permission").click(function () {
        $("input[type=checkbox]").prop('checked', $(this).prop('checked'));
    });

</script>

resources/views/admin/layouts/nav.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..."
                   aria-describedby="btnNavbarSearch"/>
            <button class="btn btn-success" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        @guest
            @if (Route::has('login'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
            @endif

            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
            @endif
        @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }}
                </a>

                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        @endguest
    </ul>
</nav>

resources/views/admin/layouts/sitenav.blade.php
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="{{ route('home') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">Interface</div>
                @hasPermission('user_view')
                <a class="nav-link" href="{{ route('users.index') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                    Users
                </a>
                @endhasPermission
                @hasPermission('role_view')
                <a class="nav-link" href="{{ route('roles.index') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Roles
                </a>
                @endhasPermission
                @hasPermission('category_view')
                <a class="nav-link" href="{{ route('categories.index') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Categories
                </a>
                @endhasPermission
                @hasPermission('product_view')
                <a class="nav-link" href="{{ route('products.index') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Products
                </a>
                @endhasPermission
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            Start Bootstrap
        </div>
    </nav>
</div>