routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Intervention\Image\Facades\Image;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth'])->group(function () {
    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_view');

        Route::get('/edit/{id}', [UserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_edit');

        Route::get('/create', [UserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::post('/', [UserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_store');

        Route::delete('/{user}', [UserController::class, 'destroy'])
            ->name('delete')
            ->middleware(['permission:user_delete', 'check.user']);

        Route::put('/{id}', [UserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('users/{id}', [UserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_show');
    });

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [RoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_view');

        Route::get('/edit/{id}', [RoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_edit');

        Route::get('/create', [RoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [RoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_store');

        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:role_delete');

        Route::put('/{id}', [RoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('users/{id}', [RoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_show');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_view');

        Route::get('/create', [ProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/edit/{id}', [ProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_edit');

        Route::put('/{id}', [ProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::post('/', [ProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_store');

        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:product_delete');

        Route::get('/{id}', [ProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_show');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_view');

        Route::get('/create', [CategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::post('/', [CategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_store');

        Route::get('/list', [CategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_view');

        Route::get('/edit/{id}', [CategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_edit');

        Route::put('/{category}', [CategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::delete('/{category}', [CategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';

    protected $fillable = [
        'name',
        'price',
        'description',
        'image'
    ];

    protected $hidden = [
        'created_at',
        'updated_at'
    ];

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    //Them Id so it
    public function scopeWithCategoryId($query, $categoryId)
    {
        return $categoryId ? $query->WhereHas('categories', function ($q) use ($categoryId) {
            $q->where('id', $categoryId);
        }) : null;
    }

    public function scopeWithMinPrice($query, $minPrice)
    {
        return $minPrice ? $query->where('price', '>=', $minPrice) : null;
    }

    public function scopeWithMaxPrice($query, $maxPrice)
    {
        return $maxPrice ? $query->where('price', '<=', $maxPrice) : null;
    }


    public function categories()
    {
        return $this->belongsToMany(
            Category::class,
            'category_product',
            'product_id',
            'category_id'
        );
    }

    public function attachCategory($categoryId)
    {
        return $this->categories()->attach($categoryId);
    }

    public function syncCategory($categoryId)
    {
        return $this->categories()->sync($categoryId);
    }

    public function detachCategory()
    {
        return $this->categories()->detach();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class ProductController extends Controller
{
    protected CategoryService $categoryService;

    protected ProductService $productService;

    /**
     * @param $product
     */
    public function __construct(CategoryService $categoryService, ProductService $productService)
    {
        $this->categoryService = $categoryService;
        $this->productService = $productService;
        View::share('categories', $this->categoryService->getAll());
    }

    public function index(Request $request)
    {
        $products = $this->productService->search($request);

        return view('admin.products.index', compact('products'));
    }

    public function create()
    {
        return view('admin.products.create');
    }

    public function store(CreateProductRequest $request)
    {
        $this->productService->create($request);

        return redirect()->route('products.index');
    }

    public function show($id)
    {
        $product = $this->productService->getById($id);

        return view('admin.products.show', compact('product'));
    }

    public function edit($id)
    {
        $product = $this->productService->getById($id);

        return view('admin.products.edit', compact('product'));
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $this->productService->update($request, $id);

        return redirect()->route('products.index');
    }

    public function destroy($id)
    {
        $this->productService->delete($id);

        return redirect()->route('products.index');
    }
}

resources/views/admin/products/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Create Product</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Product</li>
                </ol>

                <div class="container">
                    <div class="row justify-content-center">
                        <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Name</label>
                                    <input name="name" type="text" class="form-control" placeholder="Name...">
                                    @error('name')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Category</label>
                                <select class="form-select" name="category_id" aria-label="Default select example">
                                    <option selected value="">Select Category</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                                @error('category_id')
                                <div class="link-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Price</label>
                                    <input name="price" type="text" class="form-control"
                                           placeholder="Price...">
                                    @error('price')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Description</label>
                                    <input name="description" type="text" class="form-control"
                                           placeholder="Description...">
                                    @error('description')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Image</label>
                                    <input name="image" id="image" type="file" class="form-control">
                                    @error('image')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <img id="showImage"
                                         alt=""
                                         style="width: 300px;">
                                </div>

                            </div>
                            <button type="submit" class="btn btn-success">Create Product</button>
                        </form>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>w
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#image').change(function (e) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#showImage').attr('src', e.target.result);
                }
                reader.readAsDataURL(e.target.files['0']);
            })
        })
    </script>
@endpush

resources/views/admin/products/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Edit Product')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Update Product</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Product</li>
                </ol>

                <div class="container">
                    <div class="row justify-content-center">
                        <form action="{{ route('products.update', $product->id) }}" method="POST"
                              enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Name</label>
                                    <input name="name" type="text" value="{{ $product->name }}" class="form-control"
                                           placeholder="Name...">
                                    @error('name')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <label class="form-label">Category</label>
                            <select class="form-select" name="category_id[]" aria-label="Default select example">
                                @foreach($categories as $category)
                                    <option @foreach($product->categories as $p)
                                            @if($category->id == $p->id)
                                            selected="selected"
                                            @endif
                                            @endforeach
                                            value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Price</label>
                                    <input name="price" type="text" value="{{ $product->price }}" class="form-control"
                                           placeholder="Price...">
                                    @error('price')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Description</label>
                                    <input name="description" type="text" value="{{ $product->description }}"
                                           class="form-control"
                                           placeholder="Description...">
                                    @error('description')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-group">
                                    <label class="form-label">Image</label>
                                    <input name="image" id="image" type="file" value="{{ $product->image }}"
                                           class="form-control">
                                    @error('image')
                                    <div class="link-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <img id="showImage"
                                     src="{{ \Illuminate\Support\Facades\URL::to('uploads/products/' . $product->image) }}"
                                     style="width: 300px;">
                            </div>
                            <br>
                            <button type="submit" class="btn btn-success">Update Product</button>
                        </form>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>w
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#image').change(function (e) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#showImage').attr('src', e.target.result);
                }
                reader.readAsDataURL(e.target.files['0']);
            })
        })
    </script>
@endpush

resources/views/admin/products/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">Products Management</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">All Products</li>
                </ol>
                <div class="container-fluid px-4">
                    @hasPermission('product_create')
                    <a href="{{ route('products.create') }}" class="btn btn-success">Create
                        Product</a>
                    @endhasPermission
                    <div class="row justify-content-center">
                        <div class="row justify-content-center">
                            <form method="GET" class="col-md-5 m-md-3 d-flex">
                                <select name="category_id" class=" form-control col-md-2 mr-2"
                                        aria-label="Default select example">
                                    <option value="" selected>Category</option>
                                    @foreach($categories as $category)
                                        <option {{ $category->id == request('category_id') ? 'selected' : '' }}
                                                value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>

                                <input type="search" name="name" value="{{ request('name') }}" class="form-control"
                                       placeholder="search ...">

                                <div class="col-md-2">
                                    <input type="number" class="form-control" name="min_price" placeholder="Min..."
                                           value="{{ request('min_price') }}">
                                    <br>
                                    <input type="number" class="form-control" name="max_price" placeholder="Max..."
                                           value="{{ request('max_price') }}">
                                </div>

                                <button type="submit" class="btn btn-primary">
                                    search
                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Image</th>
                                <th scope="col">Name</th>
                                <th scope="col">Category</th>
                                <th scope="col">Price</th>
                                <th scope="col">Description</th>
                                <th scope="col">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($products as $product)
                                <tr>
                                    <th scope="row">{{$product->id}}</th>
                                    <td>
                                        <img src="{{ asset('uploads/products/'.$product->image) }}" width="100px" height="100px" alt="">
                                    </td>
                                    <td>{{$product->name}}</td>
                                    @foreach($product->categories as $category)
                                        <td>{{$category->name}}</td>
                                    @endforeach
                                    <td>{{$product->price . " ". "VNĐ"}}</td>
                                    <td>{{$product->description}}</td>
                                    <td>
                                        @hasPermission('product_show')
                                        <a href="{{route('products.show',$product->id)}}" class="btn btn-primary"><i
                                                class="far fa-eye"></i></a>
                                        @endhasPermission
                                        @hasPermission('product_edit')
                                        <a href="{{ route('products.edit', $product->id) }}"
                                           class="btn btn-success"><i
                                                class="far fa-edit"></i></a>
                                        @endhasPermission
                                        @hasPermission('product_delete')
                                        <button type="submit" class="btn btn-danger btn-delete"
                                                onclick="deleteProduct({{$product->id}})"><i
                                                class="fas fa-trash-alt"></i></button>
                                        @endhasPermission
                                        <form action="{{ route('products.delete', $product->id) }}"
                                              id="form-{{$product->id}}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <p class="font-weight-bold" style="text-align: center"> -- NOT FOUND DATA -- </p>
                            @endforelse
                            </tbody>
                        </table>
                        <div class="container-fluid">
                            {{$products->links()}}
                        </div>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection
@push('scripts')
    <script>
        function deleteProduct(id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    event.preventDefault();
                    document.getElementById('form-' + id).submit();
                    Swal.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/admin/products/show.blade.php
@extends('admin.layouts.app')

@section('title', 'Dashboard')

@section('content')

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">List Products</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">All Products</li>
                </ol>
                <div class="container-fluid px-4">
                    <a href="#" data-bs-toggle="modal" data-bs-target="#CreateProductModal" class="btn btn-success">Create
                        Product</a>
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <form method="GET" class="m-md-3 d-flex">
                                <input type="search" name="key" value="{{ request('key') }}" class="form-control"
                                       placeholder="search ...">
                                <button type="submit" class="btn btn-primary">
                                    search
                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Category</th>
                                <th scope="col">Price</th>
                                <th scope="col">Description</th>
                                <th scope="col">Image</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">{{$product->id}}</th>
                                <td>{{$product->name}}</td>
                                @foreach($product->categories as $category)
                                    <td>{{$category->name}}</td>
                                @endforeach
                                <td>{{$product->price}}</td>
                                <td>{{$product->description}}</td>
                                <td>
                                    <img src="{{ asset('uploads/products/'.$product->image) }}" width="80px" alt="">
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="container-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection