routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Intervention\Image\Facades\Image;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth'])->group(function () {
    Route::name('users.')->prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])
            ->name('index')
            ->middleware('permission:user_view');

        Route::get('/edit/{id}', [UserController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:user_edit');

        Route::get('/create', [UserController::class, 'create'])
            ->name('create')
            ->middleware('permission:user_create');

        Route::post('/', [UserController::class, 'store'])
            ->name('store')
            ->middleware('permission:user_store');

        Route::delete('/{user}', [UserController::class, 'destroy'])
            ->name('delete')
            ->middleware(['permission:user_delete', 'check.user']);

        Route::put('/{id}', [UserController::class, 'update'])
            ->name('update')
            ->middleware('permission:user_update');

        Route::get('users/{id}', [UserController::class, 'show'])
            ->name('show')
            ->middleware('permission:user_show');
    });

    Route::name('roles.')->prefix('roles')->group(function () {
        Route::get('/', [RoleController::class, 'index'])
            ->name('index')
            ->middleware('permission:role_view');

        Route::get('/edit/{id}', [RoleController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:role_edit');

        Route::get('/create', [RoleController::class, 'create'])
            ->name('create')
            ->middleware('permission:role_create');

        Route::post('/', [RoleController::class, 'store'])
            ->name('store')
            ->middleware('permission:role_store');

        Route::delete('/delete/{id}', [RoleController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:role_delete');

        Route::put('/{id}', [RoleController::class, 'update'])
            ->name('update')
            ->middleware('permission:role_update');

        Route::get('users/{id}', [RoleController::class, 'show'])
            ->name('show')
            ->middleware('permission:role_show');
    });

    Route::name('products.')->prefix('products')->group(function () {
        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:product_view');

        Route::get('/create', [ProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:product_create');

        Route::get('/edit/{id}', [ProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:product_edit');

        Route::put('/{id}', [ProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:product_update');

        Route::post('/', [ProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:product_store');

        Route::delete('/delete/{id}', [ProductController::class, 'destroy'])
            ->name('delete')
            ->middleware('permission:product_delete');

        Route::get('/{id}', [ProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:product_show');
    });

    Route::name('categories.')->prefix('categories')->group(function () {
        Route::get('/', [CategoryController::class, 'index'])
            ->name('index')
            ->middleware('permission:category_view');

        Route::get('/create', [CategoryController::class, 'create'])
            ->name('create')
            ->middleware('permission:category_create');

        Route::post('/', [CategoryController::class, 'store'])
            ->name('store')
            ->middleware('permission:category_store');

        Route::get('/list', [CategoryController::class, 'list'])
            ->name('list')
            ->middleware('permission:category_view');

        Route::get('/edit/{id}', [CategoryController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:category_edit');

        Route::put('/{category}', [CategoryController::class, 'update'])
            ->name('update')
            ->middleware('permission:category_update');

        Route::delete('/{category}', [CategoryController::class, 'destroy'])
            ->name('destroy')
            ->middleware('permission:category_delete');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    // Accessor append into json or array
    protected $appends = ['parent_category_name'];

    protected $table = 'categories';

    protected $fillable = [
        'parent_id',
        'name'
    ];

    public function products()
    {
        return $this->hasMany(Product::class, 'category_id', 'product_id');
    }

    public function parentCategory()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    // Define accessor
    public function getParentCategoryNameAttribute()
    {
        return $this->parentCategory ? $this->parentCategory->name : null;
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\CreateNewCategoryRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    protected CategoryService $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index(Request $request)
    {
        $categories = $this->categoryService->search($request);

        $parentIds = $this->categoryService->getParentIds();
        return view('admin.categories.index', compact('categories', 'parentIds'));
    }

    public function list(Request $request)
    {
        $categories = $this->categoryService->search($request);
        return view('admin.categories.list', compact('categories'))->render();
    }

    public function create()
    {
        return view('admin.categories.index', ['categories'=>$this->categoryService->getParent()]);
    }

    public function store(CreateNewCategoryRequest $request)
    {
        $this->categoryService->store($request);
        return response()->json([
            'status' => Response::HTTP_OK,
            'message' => 'Create Category Successfully!'
        ]);
    }

    public function edit($id)
    {
        $category = $this->categoryService->findById($id);
        return response()->json([
            'status' => Response::HTTP_OK,
            'category'=> $category
        ]);
    }

    public function update(CreateNewCategoryRequest $request, $id)
    {
        $this->categoryService->update($request, $id);
        return response()->json([
            'status' => Response::HTTP_OK,
            'message' => 'Update Category Success !!!',
        ]);
    }

    public function destroy($id)
    {
        $this->categoryService->delete($id);
        return response()->json([
            'status' => Response::HTTP_OK,
            'message'=>'Data delete succesfully!'
        ]);
    }
}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Categories')

@section('content')
    <!--Create Modal -->
    <div class="modal fade" id="CreateCategoryModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form id="CreateCategoryForm" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <ul class="alert alert-warning d-none" id="_error_create"></ul>
                        <div class="form-group mb-3">
                            <label>Name</label>
                            <input type="text" class="form-control" id="nameCreate" name="name">
                            <span class="text-danger name_error_create"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label>ParentID</label>
                            <select class="form-control" id="parentIdCreate" name="parent_id">
                                <option value="">Chọn danh mục</option>
                                @foreach($parentIds as $parentId)
                                    <option value="{{$parentId->id}}">{{$parentId->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary btn-create"
                                data-action="{{route('categories.store')}}">Save
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!--Edit Modal -->
    <div class="modal fade" id="EditCategoryModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form id="EditCategoryForm" enctype="multipart/form-data">
                    <div class="modal-body">
                        <ul class="alert alert-warning d-none" id="_error_update"></ul>
                        <div class="form-group mb-3">
                            <label>Name</label>
                            <input type="text" class="form-control" id="nameUpdate" name="name">
                            <span class="text-danger name_error_update"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label>ParentID</label>
                            <select class="form-control" id="parentIdUpdate" name="parent_id">
                                <option value="">Chọn danh mục</option>
                                @foreach($parentIds as $parentId)
                                    <option value="{{$parentId->id}}">{{$parentId->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary btn-update">Update
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-4">List Categories</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">All Category</li>
                </ol>
                <div class="container-fluid px-4">
                    @hasPermission('category_create')
                    <a href="#" data-bs-toggle="modal" data-bs-target="#CreateCategoryModal" class="btn btn-success">Create
                        Category</a>
                    @endhasPermission
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <form method="GET" class="m-md-3 d-flex">
                                <input type="search" name="name" id="name" value="{{ request('name') }}"
                                       class="form-control"
                                       placeholder="search ...">
                            </form>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div id="success_message">
                        </div>
                        <div id="list" data-action="{{route('categories.list')}}">
                        </div>
                    </div>
                </div>

            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('admin/js/category.js') }}"></script>
@endpush

resources/views/admin/categories/list.blade.php
<div id="list" data-action="{{route('categories.list')}}">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Parent Name</th>
            <th scope="col">Created Date</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @forelse($categories as $category)
            <tr>
                <th scope="row">{{$category->id}}</th>
                <td>{{$category->name}}</td>
                <td>
                    {{ $category->ParentCategoryName }}
                </td>
                @foreach($category->products as $product)
                    <td>{{ $product ? $product->count() : 0 }}</td>
                @endforeach
                <td>{{ $category->created_at ? $category->created_at->format('d-m-Y') . ", " . $category->created_at->diffForHumans() : '01-01-1990' }}</td>
                <td>
                    @hasPermission('category_edit')
                    <a href="" class="btn btn-success btn-edit" data-bs-toggle="modal" --}}
                       data-bs-target="#EditCategoryModal" data-action="{{route('categories.edit',$category->id)}}"
                       data-update="{{route('categories.update',$category->id)}}"><i
                            class="far fa-edit"></i></a>
                    @endhasPermission
                    @hasPermission('category_delete')
                    <button type="submit" class="btn btn-danger btn-delete" onclick="deleteCategory({{$category->id}})">
                        <i class="fas fa-trash-alt"></i></button>
                    @endhasPermission
                    <form action="{{ route('categories.destroy', $category->id)}}" id="form-{{$category->id}}"
                          method="POST"
                          style="display: none">
                        @method('DELETE')
                        @csrf
                    </form>
                </td>
            </tr>
        @empty
            <p class="font-weight-bold" style="text-align: center"> -- NOT FOUND DATA -- </p>
        @endforelse
        </tbody>
    </table>
    <div class="container-fluid">
        {{$categories->links()}}
    </div>
</div>